name: Schedule Python Script

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the desired Python version

      - name: Run Python script
        run: python Code.py
